services:
  - type: web
    name: telegram-spy-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python spy.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9